# Generated by Django 5.1.7 on 2025-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('soins_peau', 'Soins de peau'), ('maquillage', 'Maquillage'), ('cheveux', 'Cheveux'), ('autres', 'Autres')], max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredients', models.TextField()),
                ('quantite_stock', models.IntegerField()),
                ('date_peremption', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
